Update arcoupdate

diff --git a/arcoupdate b/arcoupdate
--- a/arcoupdate
+++ b/arcoupdate
@@ -4,23 +4,23 @@
 # Make sure each command executes properly
 check_exit_status() {
 
-    if ! check_exit_status
-    then
-        echo
-        echo "Success"
-        echo
-    else
-        echo
-        echo "[ERROR] Process Failed!"
-        echo
+	if [ $? -eq 0 ]
+	then
+		echo
+		echo "Success"
+		echo
+	else
+		echo
+		echo "[ERROR] Process Failed!"
+		echo
 		
-        read -r -p "The last command exited with an error. Exit script? (yes/no) " answer
+		read -p "The last command exited with an error. Exit script? (yes/no) " answer
 
-        if [ "$answer" == "yes" ]
-        then
-            exit 1
-        fi
-    fi
+            if [ "$answer" == "y" ]
+            then
+                exit 1
+            fi
+	fi
 }
 
 greeting() {
@@ -30,60 +30,75 @@ greeting() {
     echo
 }
 
-# Download and install all Arch Linux and ArcoLinux packages
-general_update() {
+# search for the fastest mirrors
+function mirror() {
 
-    sudo update -y;
+	echo "Updating your Mirrors."
+	sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist;
+	check_exit_status
+}
+
+# Download and install all Arch Linux and ArcoLinux packages
+function general_update() {
+
+	echo "Updating Arch & Arco."
+    sudo pacman -Syyu -y;
     check_exit_status
 }
 
 # Copy/paste all config files from /etc/skel to your home directory
-skel() {
+function skel() {
 
-    skel;
+	echo "Running Skel."
+    'cp -rf /etc/skel/* ~';
     check_exit_status
 }
 
 # Put the fancy bash promt back after updating
-fix_bashrc() {
+function fix_bashrc() {
 
+	echo "Putting Bashrc back together."
     echo "source ~/.fancy-bash-promt.sh" >> ~/.bashrc-latest
     check_exit_status
 }
 
 # Copy over all new bashrc changes, including fix_bashrc
-copy_over_newest_bashrc() {
+function copy_over_newest_bashrc() {
 
-    cb;
+    'cp ~/.bashrc-latest ~/.bashrc && source ~/.bashrc && sudo cp /etc/skel/.bashrc-latest /etc/skel/.bashrc';
     check_exit_status
 }
 
 # Now update the rest – Only AUR packages will now be updated
-aur_update() {
+function aur_update() {
 
-    sudo pksyua -y;
+	echo "Updating the AUR."
+    yay -Syu --noconfirm;
     check_exit_status
 }
 
 # Perform the maintenance and clean-up duties, remove orphaned files to keep the system running optimally
-housekeeping() {
+function housekeeping() {
 
-    sudo cleanup -y;
+	echo "Cleaning up."
+    sudo pacman -Rns $(pacman -Qtdq) -y;
     check_exit_status
 }
 
-leave() {
+function leave() {
 
     echo
     echo "-------------------------------"
     echo "- ArcoLinux has been updated! -"
     echo "-------------------------------"
     echo
+    echo "Now Stay Rolling."
     cd "$HOME/.bin/stay-rolling" && ls;
     exit
 }
 
 greeting
+mirror
 general_update
 skel
 fix_bashrc
